Many simplifications

diff --git a/jobhours b/jobhours
--- a/jobhours
+++ b/jobhours
@@ -1,23 +1,19 @@
 #!/bin/bash -e
 
-if [[ -d ./org2tc ]]; then
-    export PATH=$PWD/org2tc:$PATH
+if [[ ! -f "$1" ]]; then
+    echo "Usage: jobhours <Org-mode file containing CLOCK data>"
+    exit 1
 fi
 
-if [[ -d ./dist/build/process-hours ]]; then
-    export PATH=$PWD/dist/build/process-hours:$PATH
+if [[ ! -x "$(which jq)" ]]; then
+    echo "Error: jobhours requires the 'jq' utility to be installed"
+    exit 1
 fi
 
-if [[ -d ./dist/build/bae-periods ]]; then
-    export PATH=$PWD/dist/build/bae-periods:$PATH
+if [[ ! -x "$(which org2tc)" ]]; then
+    echo "Error: jobhours requires the 'org2tc' utility to be installed"
+    exit 1
 fi
-
-if [[ -d ./dist/build/timelog-periods ]]; then
-    export PATH=$PWD/dist/build/timelog-periods:$PATH
-fi
-
-START=$(bae-periods | grep ^start | cut -c8-)
-FINISH=$(bae-periods | grep ^finish | cut -c9-)
 
 function parseorg() {
     ORG_START=$(echo "$1" | cut -c-19)
@@ -27,5 +23,15 @@ function parseorg() {
         | timelog-periods --begin "$1" --end "$2" --file -
 }
 
-process-hours --ideal <(bae-periods)                            \
-              --real  <(parseorg "$START" "$FINISH" "$1")
+periods=$(mktemp -t bae-periods.XXXXXXXX)
+function finish {
+  rm -f "$periods"
+}
+trap finish EXIT
+
+bae-periods --there > "$periods"
+
+START=$(jq -r .start "$periods")
+FINISH=$(jq -r .finish "$periods")
+
+process-hours --ideal "$periods" --real <(parseorg "$START" "$FINISH" "$1")
